const actionTypes = {
    SET_MNEMONIC: 'SET_MNEMONIC',
    ADD_TOKEN: 'ADD_TOKEN',
    REMOVE_TOKEN: 'REMOVE_TOKEN',
    UPDATE_TOKEN_BALANCE: 'UPDATE_TOKEN_BALANCE',
    UPDATE_ALL_BALANCES: 'UPATE_ALL_TOKEN_BALANCES',
    SET_TOKEN_BALANCE: 'SET_TOKEN_BALANCE',
};

export default actionTypes;
