const actionTypes = {
    TOGGLE_ADD_TOKEN: 'TOGGLE_ADD_TOKEN',
    OPEN_TOKEN_SEARCH: 'OPEN_TOKEN_SEARCH',
    CLOSE_TOKEN_SEARCH: 'CLOSE_TOKEN_SEARCH',
    OPEN_ADD_BY_ADDRESS: 'OPEN_ADD_BY_ADDRESS',
    CLOSE_ADD_BY_ADDRESS: 'CLOSE_ADD_BY_ADDRESS',
};

export default actionTypes;
